### ISSUE TITLE
Flaky testIncDec test

### ISSUE THREAD

**Issue by felipecsl** [RedisTimeSeries/JRedisTimeSeries#24]
This test is occasionally failing for me when running locally, seems flaky:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.redislabs.redistimeseries.RedisTimeSeriesTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.495 sec <<< FAILURE! - in com.redislabs.redistimeseries.RedisTimeSeriesTest
testIncDec(com.redislabs.redistimeseries.RedisTimeSeriesTest)  Time elapsed: 0.019 sec  <<< ERROR!
redis.clients.jedis.exceptions.JedisDataException: TSDB: for incrby/decrby, timestamp should be newer than the lastest one
	at com.redislabs.redistimeseries.RedisTimeSeriesTest.testIncDec(RedisTimeSeriesTest.java:322)


Results :

Tests in error:
  RedisTimeSeriesTest.testIncDec:322 » JedisData TSDB: for incrby/decrby, timest...

Tests run: 12, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by gkorland** [comment]
Yes it seems like there is a timing issue in this test

**Comment by ashtul** [comment]
@felipecsl 
The first time you call ts.incrby you are using the implicit server Unix time. The second time you are using the time from your laptop. 
This means your second timestamp might be prior to the first one and you will get an error. 
Please note, ts.incrby will update the latest value if it has the same timestamp as the latest sample. If it earlier than the latest, you will get the error message "ts.incrtby...". 
I would suggest to remove this test as it might depend on the system on which it is ran.

**Comment by felipecsl** [comment]
you could easily work around that issue by using a current time provider that you could override during tests using a fixed current time. if you don't care about fixing it, then by all means delete the test :)

**Comment by filipecosta90** [comment]
> you could easily work around that issue by using a current time provider that you could override during tests using a fixed current time. if you don't care about fixing it, then by all means delete the test :)

Agree @felipecsl - given that we want to test incrby and decrby and not the auto-ts feature on this test. The PR #26 addresses this issue.
