### ISSUE TITLE
[Need Info] TS.INCRBY/TS.DECRBY with labels

### ISSUE THREAD

**Issue by RajvanshR** [RedisTimeSeries/JRedisTimeSeries#28]
I can find the TS.INCRBY/TS.DECRBY command with key value and TIMESTAMP. Is there a option to add these along with LABELS ?

As per the documentation [https://oss.redislabs.com/redistimeseries/commands/](url) am looking for below command.

`TS.INCRBY key value [TIMESTAMP timestamp] [LABELS label value..]` .

**Comment by ashtul** [comment]
@RajvanshR 
If I understand, you want to add labels to a series using the TS.INCRBY command.

**Comment by RajvanshR** [comment]
Thanks @ashtul
