### ISSUE TITLE
Add support for CHUNK_SIZE and ON_DUPLICATE options with create

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/JRedisTimeSeries#31]
The create API is missing some options from the official documentation, namely  CHUNK_SIZE and ON_DUPLICATE.

**Comment by gkorland** [comment]
ref #29

**Comment by gkorland** [comment]
@lpellegr thanks for the issue please see the PR

**Comment by lpellegr** [comment]
Great, thanks for the quick PR.
