### ISSUE TITLE
Support for connection closing

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/JRedisTimeSeries#33]
Using the library, I cannot find a way to close the internal connection(s) properly (e.g. a close or shutdown method). That's quite a real issue for use in production.

**Comment by gkorland** [comment]
You're right we should add such an API, as a work around you can use this constructor:

[public RedisTimeSeries​(redis.clients.jedis.util.Pool<redis.clients.jedis.Jedis> pool)](https://www.javadoc.io/doc/com.redislabs/jredistimeseries/latest/com/redislabs/redistimeseries/RedisTimeSeries.html)

And just close the pool when you're done with the RedisTimeSeries​ connection.
