### ISSUE TITLE
Support initialization from a Redis connection String

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/JRedisTimeSeries#34]
This client library does not support initializing a client from a connection string or URI. For instance, in an app I am working on, I receive a Redis connection string as input. Due to the lack of support for such input in the client library, I have to parse the String by myself or change the way connection data are passed. 

All libraries I know support passing a connection String to initialize a connection to a database. Adding support should be quite easy since the underlying _Jedis_ library that is used supports the use case. If you agree to fix this issue, the main issue is whether you prefer to support a String, a URI, or both as input.

**Comment by gkorland** [comment]
To avoid duplicating all the Jedis settings we added this construction, that allows you to pass a Jedis pool that is configured the way you want it.

[public RedisTimeSeries​(redis.clients.jedis.util.Pool<redis.clients.jedis.Jedis> pool)](https://www.javadoc.io/doc/com.redislabs/jredistimeseries/latest/com/redislabs/redistimeseries/RedisTimeSeries.html)
