### ISSUE TITLE
Support for username when connecting to a Redis instance

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/JRedisTimeSeries#35]
Another issue for use in production in my case, the constructors provided with the library does not allow passing a username for connecting to a Redis 6 instance whose connection is made with a username/password couple and not only a password.

**Comment by gkorland** [comment]
To avoid duplicating all the Jedis settings we added this construction, that allows you to pass a Jedis pool that is configured the way you want it.

[public RedisTimeSeries​(redis.clients.jedis.util.Pool<redis.clients.jedis.Jedis> pool)](https://www.javadoc.io/doc/com.redislabs/jredistimeseries/latest/com/redislabs/redistimeseries/RedisTimeSeries.html)
