### ISSUE TITLE
Using `-` and `+` with range and mrange

### ISSUE THREAD

**Issue by lpellegr** [RedisTimeSeries/JRedisTimeSeries#36]
I think it's more a question than an issue but it seems there is something that could be at least documented in the library documentation. 

When you use `range` or `mrange`, the type for _from_ and _to_ parameters is _long_. My question is how to use the special characters `-` and `+` to respectively to express the minimum possible timestamp and the maximum possible timestamp. 

I guess using 0 and a very large number should work the same but I thought it was worth creating an issue to at least improve the documentation.

**Comment by gkorland** [comment]
@lpellegr yes you're right, you should just use Long.MIN_VALUE and Long.MAX_VALUE
