### ISSUE TITLE
Issue with implementation of MRange and MRevRange

### ISSUE THREAD

**Issue by shankarshastri** [RedisTimeSeries/JRedisTimeSeries#75]
Few functions mrange and mrevrange takes in primitive type long rather than Long, as a result when the user passes null the value becomes 0 due to the primitive nature.

**Comment by sazzad16** [comment]
@shankarshastri 

> when the user passes null the value becomes 0

No. It throws NullPointerException, right away.

**Comment by shankarshastri** [comment]
@sazzad16 , Can you explain to me where in code is it throwing an exception?

This public method for example which is available for users to use:
`  public Range[] mrange(long from, long to, String... filters) { `

When we pass `mrange(null, null, "id=1")`, it will consider from and to as 0.

Very similar to this there are a lot of functions using primitive long rather than Long.

**Comment by sazzad16** [comment]
@shankarshastri 

`mrange(null, null, "id=1")` is not possible in Java. Any decent IDE would show this as an error.
![Screenshot from 2021-09-25 11-36-30](https://user-images.githubusercontent.com/7600764/134759970-800a5188-db7a-4bca-961b-a52316eee102.png)
Irrespective of IDE, any execution attempt would cause compilation error.

And, any Long carrying null would cause NullPointerException.
![Screenshot from 2021-09-25 11-38-44](https://user-images.githubusercontent.com/7600764/134760034-1c76f98b-9473-4f23-80bb-509e8b9fda58.png)

Your claim doesn't seem to align with Java.
