### ISSUE TITLE
Support for database index

### ISSUE THREAD

**Issue by yusuf-kh** [RedisTimeSeries/JRedisTimeSeries#78]
Hey currently JRedisTimeseries doesn't have support for choosing a Redis Database.

I get that since you can create a RedisTimeseries Object by passing a Jedis Pool, and you can only select a database index after using getResource() from the JedisPool, you might not be able to add a index from using that constructor. But is it possible to add an attribute to this class for selecting a database index?

**Comment by sazzad16** [comment]
@yusuf-kh You can create your own JedisPool using a constructor with database param and pass that JedisPool in JRedisTimeseries constructor.

**Comment by yusuf-kh** [comment]
@sazzad16 Thanks, i had missed that constructor
